import os
import sys

out_content = "#pragma once\n\n// GENERATED BY scripts/gen_shaders_header.py \n\n"
shaders_path = sys.argv[1]
header_path = sys.argv[2]

for file_name in os.listdir(shaders_path):
    with open(os.path.join(shaders_path, file_name)) as f:
        shader_content = f.read()
        shader_content = shader_content.replace("\n", "\\n").replace("\"", "\\\"")

        var_name = file_name.replace(".", "_")
        var_name = f"_shader_{var_name}_data"

        out_content += f"static const char* {var_name} = \"{shader_content}\";\n"

with open(header_path, mode="w") as out_file:
    out_file.write(out_content)
